// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLmgK-2fiYbbAomDd8MMfZqgYsM_64J9E',
    appId: '1:401528360308:web:4904c792b327de5ee4f021',
    messagingSenderId: '401528360308',
    projectId: 'my-wallet-4b7b7',
    authDomain: 'my-wallet-4b7b7.firebaseapp.com',
    storageBucket: 'my-wallet-4b7b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOfsvgZ6umSUp-876_h0xc-QWZ2KWC_tg',
    appId: '1:401528360308:android:af714c2ccc354abce4f021',
    messagingSenderId: '401528360308',
    projectId: 'my-wallet-4b7b7',
    storageBucket: 'my-wallet-4b7b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmrThctCchJPcsXiOm7yG_D4Moo6n0cJM',
    appId: '1:401528360308:ios:cfbf442cbc8bebcae4f021',
    messagingSenderId: '401528360308',
    projectId: 'my-wallet-4b7b7',
    storageBucket: 'my-wallet-4b7b7.firebasestorage.app',
    iosClientId: '401528360308-cm92on33764n9fq91neuq5s4r2rm1s74.apps.googleusercontent.com',
    iosBundleId: 'com.example.myWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmrThctCchJPcsXiOm7yG_D4Moo6n0cJM',
    appId: '1:401528360308:ios:cfbf442cbc8bebcae4f021',
    messagingSenderId: '401528360308',
    projectId: 'my-wallet-4b7b7',
    storageBucket: 'my-wallet-4b7b7.firebasestorage.app',
    iosClientId: '401528360308-cm92on33764n9fq91neuq5s4r2rm1s74.apps.googleusercontent.com',
    iosBundleId: 'com.example.myWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLmgK-2fiYbbAomDd8MMfZqgYsM_64J9E',
    appId: '1:401528360308:web:01b2d8dcad776937e4f021',
    messagingSenderId: '401528360308',
    projectId: 'my-wallet-4b7b7',
    authDomain: 'my-wallet-4b7b7.firebaseapp.com',
    storageBucket: 'my-wallet-4b7b7.firebasestorage.app',
  );
}
